name = "spino-gambinocasino-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambinocasino.com.es"
HMAC_KEY = "c081872890ce2e092f312bb2a898c4b8617b0ab2239ee6786384e1ae2fd0f61f"
COOKIE_NAME = "30f"
PLAY_PATH = "launch"
BUTTON_ID = "p54f7f54923e0187e5523b7614f6e986b"
GATE_SALT = "89b7a7dfc076da38"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "g85r"
CTA_SELECTOR = ".play-button"
